export const GET_ERRORS="GET_ERRORS";
export const USER_LOADING="USER_LOADING";
export const SET_CURRENT_USER="SET_CURRENT_USER";

export const FETCH_CURRENT_LIST="FETCH_CURRENT_LIST";
export const UPDATED_LIST="UPDATED_LIST";
export const CREATE_LIST="CREATE_LIST";

export const UPDATE_BUDGET="UPDATE_BUDGET";

export const CREATE_EVENT="CREATE_EVENT";
export const FETCH_CURRENT_EVENTS="FETCH_CURRENT_EVENTS";
export const UPDATED_EVENT=" UPDATED_EVENT";
export const CREATE_EVENT_LIST="CREATE_EVENT_LIST";
export const SET_UPDATE_ID="SET_UPDATE_ID";